name: Aula
version: '${version}'
main: net.gahvila.aula.Aula
load: STARTUP
authors: [ Jokni ]
api-version: '1.21'
dependencies:
  server:
    WorldGuard:
      required: true
    GahvilaCore:
      required: true

